baseURL = "https://buildbrighton.com/"
languageCode = "en-gb"
title = "Build Brighton"
enableRobotsTXT = true

[params]
bbmsHome = "https://bbms.buildbrighton.com/"
bbmsJoin = "https://bbms.buildbrighton.com/register"
